export const CREATE_CATEGORY_PENDING = 'CREATE_CATEGORY_PENDING'
export const  CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS'
export const CREATE_CATEGORY_ERROR = 'CREATE_CATEGORY_ERROR'

export const CREATE_EXPENSE_PENDING = 'CREATE_EXPENSE_PENDING'
export const  CREATE_EXPENSE_SUCCESS = 'CREATE_EXPENSE_SUCCESS'
export const CREATE_EXPENSE_ERROR = 'CREATE_EXPENSE_ERROR'

export const DELETE_LOADING = 'DELETE_LOADING';
export const DELETE_SUCCESS = 'DELETE_SUCCESS';
export const DELETE_ERROR = 'DELETE_ERROR';

export const DELETE_CATEGORY_LOADING = 'DELETE_CATEGORY_LOADING';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_ERROR = 'DELETE_CATEGORY_ERROR';